### ISSUE TITLE
estimateCellCounts with EPIC array

### ISSUE THREAD

**Issue by YinanZheng** [kasperdanielhansen/minfi#70]
Hello,

I seems current estimateCellCounts function does not support EPIC array. Is it possible that future version will add this feature or the algorithm itself may not work for EPIC array at all (e.g. missing signature CpGs in EPIC)?

Than you.

**Comment by Jfortin1** [comment]
Hi Yinan,

We are actually currently working on that and should release something in the next couple of days hopefully.

JP

**Comment by YinanZheng** [comment]
Glad to hear that. Thank you for your great work!

**Comment by Jfortin1** [comment]
We have now fixed the issue. The function estimateCellCounts() now takes EPIC array as input. We describe the changes in our bioRxiv preprint: http://biorxiv.org/content/early/2016/07/23/065490

**Comment by MeganBreitbach** [comment]
I am still getting an error when trying to estimate cell counts with EPIC data. 

> cellCounts_epic <- estimateCellCounts(RGset_epic)
Loading required package: FlowSorted.Blood.EPIC
Error in estimateCellCounts(RGset_epic) : 
  Could not find reference data package for compositeCellType 'Blood' and platform 'EPIC' (inferred package name is 'FlowSorted.Blood.EPIC')
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘FlowSorted.Blood.EPIC’

I have tried to load the  ‘FlowSorted.Blood.EPIC’ package, but also get this error- 

> biocLite('FlowSorted.Blood.EPIC')
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.3 (BiocInstaller 1.22.3), R 3.3.1 (2016-06-21).
Installing package(s) ‘FlowSorted.Blood.EPIC’
Warning message:
package ‘FlowSorted.Blood.EPIC’ is not available (for R version 3.3.1) 

Additionally, I have read the bioRxiv reprint and repo in which you describe a new combineArrayTypes() function. However, there is no such function that I can find in the minfi package. Has it been included in the package yet?

**Comment by kasperdanielhansen** [comment]
Are you using Bioconductor stable or Bioconductor devel?  All of
Bioconductor is released every 6 months and we have no control over that.
You need to use the devel version to get the new stuff.

Also, we should really better document how to do this; you first need to
convert the EPIC array to 450k and then send it through estimateCellCounts.

This might help:
  https://github.com/hansenlab/EPIC450k_repro/blob/master/analysis/cell.R

Best,
Kasper

**Comment by MeganBreitbach** [comment]
I have tried everything you have suggested and am still unable to use the combineArrays and convertArray functions. 

I searched for both the combineArrays and convertArray functions in the help function of R and received this message -
Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/minfi/help/minfi.rdb' is corrupt

**Comment by kasperdanielhansen** [comment]
Well, that error suggests you have some installation issues.  I would
reinstall the package.

But tell me the output of
  sessionInfo()
after you have loaded minfi and also
  source("http://www.bioconductor.org/biocLite.R")
  biocValid()

Kasper

**Comment by MeganBreitbach** [comment]
That worked. Here is the output-

> source("http://www.bioconductor.org/biocLite.R")
Bioconductor version 3.4 (BiocInstaller 1.23.9), ?biocLite for help
> biocValid()
[1] TRUE
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.23.9

loaded via a namespace (and not attached):
[1] tools_3.3.1

Thanks so much!

**Comment by kasperdanielhansen** [comment]
solved; closing.
